lib/javascript/sarcasterXO.pwdGenerator.js

feat: pwd generator

---

lib/javascript/sarcasterXO.pwdGenerator.js
yourCard/data.json

chore: add myself in data.json

---

yourCard/data.json

feat: my profile

---

yourCard/data.json

added my name

---

yourCard/data.json

feat:My profile

---

yourCard/data.json

Adding myself as a contributor

my profile

---

lib/javascript/sam.div.js

feat : div function

---

lib/javascript/sam.addition.js

feat : add addition function

---

lib/javascript/AbbuUXG.divide.js

My Divide function

---

lib/javascript/AbbuUXG.sub.js

My Sub Function is ready

---

lib/javascript/AbbuUXG.addition.js

My Addition Function

---

lib/c/remelem.c

feat: remove element

---

lib/c/multiplicationtable.c

multiplicationtable

---

lib/c/add.c
lib/javascript/div.js
lib/javascript/sub.js

feat: add div

---

lib/javascript/mbm.addition.js

feat: addition

---

lib/c/lesgeddit.pall.c

This is a program to check if a given string is a pallindrome or not :)

Pallindrome in c

---

lib/cpp/Mubashir-Md.fibonacci.cpp

Solved Issue #62 -- Fibonacci series program in C++

Fibonacci series in C++

---

lib/cpp/NawaidAhmed.fabonacci.cpp
lib/cpp/Nawaidahmed.addnumber.cpp

It describe about the multipication table program

Fourth pull request

---

lib/cpp/NawaidAhmed.fabonacci.cpp
lib/cpp/Nawaidahmed.addnumber.cpp

Third pull request 

---

lib/cpp/NawaidAhmed.fabonacci.cpp
lib/cpp/Nawaidahmed.addnumber.cpp

Fibonacci series  

---

lib/javascript/vox.div.js

feat: div function

---

lib/cpp/BubbleSort.py

ashishgogula.BubbleSort.py

---

lib/python/linkedlist.py

ashishgogula.linkedlist.py

---

lib/python/tic-tac-toe.py

ashishgogula.tic-tac-toe.py

---

lib/javascript/vox.sub.js

feat: add sub function

---

lib/javascript/vox.addition.js

feat: add addition function

---

lib/python/calculator.py

ashishgogula.calculator.py

---

Factorial.java

try to follow the execution of the program to spot the flaw in the logic

Factorial.java

---

Factorial.c

factorial of a number

---

SumOfTwoNum.java

select  a language.
understand the basic logic.
using function for the main addition logic.
checking for errors.

SumOfTwoNum.java

---

lib/java/Armstrong.java

ashish.Armstrong.java

---

lib/java/Perfect-number.java

ashish.Perfect-number.java

---

lib/python/multiplicationTable.py

This program generates multiplication table till 10 times. It's an easy and simple program.

 multiplicationTable.py

---

lib/cpp/naziya2002.febonaci.cpp
lib/javascript/naziya2002.addition.js
lib/javascript/naziya2002.removeelement.js
yourCard/data.json

Naziya Anjum profile

---

lib/cpp/fibonacciSeries.cpp

This program represents Fibonacci series

 fibonacciSeries.cpp

---

lib/python/tipCalculator.py

This program represents tip calculator which tells a person how much tip is to be given ,splitting of bill and how much a person should pay individually.

tipCalculator.py

---

lib/c/add_using_func.c

First we must write the function prototype followed by function call and function definition.

Addition of two no.s using functions

---

lib/addition.c

addition.c

---

lib/javascript/calculator.js

Calculator.js

---

lib/javascript/harry.addition.js

feat:add addition function

---

lib/javascript/harry.addition.js
lib/javascript/harry.sub.js

sub function

---

lib/javascript/harry.div.js

division function by harshit

---

lib/c/abdulrehman.adition.c
yourCard/data.json

my 2nd push

---

lib/javascript/rukh.addition.js
yourCard/data.json

Addition by rukhsar

---

lib/javascript/rukh.addition.js
lib/javascript/rukh.sub.js
yourCard/data.json

Subtraction function 

---

lib/javascript/rukh.div.js
yourCard/data.json

Division function by rukhsar

---

lib/javascript/countdowntimer.js

countdowntimer (#56)

---

lib/Numpattern.js

The pattern can be displayed by accepting the number of rows as input from the user.
Nested for loops are used to print the pattern.

Numpattern.js

---

lib/javascript/WhileFibonacci.js

First term is Initialized to 0.
Second term is initialized to 1.
Third term= first + second.
The number of terms is accepted by user as input.
A while loop is used to print Fibonacci series up to given terms.

WhileFibonacci.js

---

lib/c/pattern_in_c.c

interesting topic of patterns in c 
input : if we give 5 
output : *
**
***
****
*****
it gives patterns in left increasing right angle triangular format

pattern in c

---

lib/python/concatination_of_2_string.py

input : str1: hello
str2: world
output : helloworld

Concatination of 2 strings in python

---

lib/python/multiply_2_numbers.py

input : num_1= 33
num_2=17
output : product = 561

multiplication of 2 numbers

---

lib/python/Area_of_circle.py

AREA of CIRCLE IN PYTHON

---

lib/c/Remove_an_element_from_Array.c

/*        program to remove a value from an array 
input : 3 4 5 7 8
position to remove an element : 2
output : 3 5 7 8 
*/

Remove an element from an array

---

lib/c/fibonacci_using_for_loop.c

fibonacci series in c for n terms using for loop

---

lib/c/NUMBER_OF_A_IN_SENTENCE.c

SIMPLE PROGRAM TO FIND NUMBER OF A'S IN A SENTENCE

NUMBER_OF_A_IN_SENTENCE.c

---

lib/python/covert_string_into_tuple.py

convert string into tuple

---

lib/python/strToTuple.py
lib/python/tipCalculator.py

1. split the string into list of integers using split method
2. then type cast it into tuple

added string to tuple in python utitlity library
